// GENERATED; DO NOT EDIT
#ifndef RFFI_UPCALLSINDEX_H
#define RFFI_UPCALLSINDEX_H

#define ATTRIB_x 0
#define CAAR_x 1
#define CAD4R_x 2
#define CADDDR_x 3
#define CADDR_x 4
#define CADR_x 5
#define CAR_x 6
#define CDAR_x 7
#define CDDDR_x 8
#define CDDR_x 9
#define CDR_x 10
#define CLOENV_x 11
#define COMPLEX_x 12
#define DUPLICATE_ATTRIB_x 13
#define ENCLOS_x 14
#define FASTR_getConnectionChar_x 15
#define GetRNGstate_x 16
#define INTEGER_x 17
#define IS_S4_OBJECT_x 18
#define LENGTH_x 19
#define LOGICAL_x 20
#define NAMED_x 21
#define OBJECT_x 22
#define PRCODE_x 23
#define PRENV_x 24
#define PRINTNAME_x 25
#define PRSEEN_x 26
#define PRVALUE_x 27
#define PutRNGstate_x 28
#define RAW_x 29
#define RDEBUG_x 30
#define REAL_x 31
#define RSTEP_x 32
#define R_BaseEnv_x 33
#define R_BaseNamespace_x 34
#define R_BindingIsLocked_x 35
#define R_CHAR_x 36
#define R_CleanUp_x 37
#define R_ExternalPtrAddr_x 38
#define R_ExternalPtrProtected_x 39
#define R_ExternalPtrTag_x 40
#define R_FindNamespace_x 41
#define R_GetConnection_x 42
#define R_GlobalContext_x 43
#define R_GlobalEnv_x 44
#define R_Home_x 45
#define R_HomeDir_x 46
#define R_Interactive_x 47
#define R_LockBinding_x 48
#define R_MakeExternalPtr_x 49
#define R_MethodsNamespace_x 50
#define R_NamespaceRegistry_x 51
#define R_NewHashedEnv_x 52
#define R_ParseVector_x 53
#define R_PreserveObject_x 54
#define R_PromiseExpr_x 55
#define R_ProtectWithIndex_x 56
#define R_ReadConnection_x 57
#define R_ReleaseObject_x 58
#define R_Reprotect_x 59
#define R_SetExternalPtrAddr_x 60
#define R_SetExternalPtrProtected_x 61
#define R_SetExternalPtrTag_x 62
#define R_TempDir_x 63
#define R_ToplevelExec_x 64
#define R_WriteConnection_x 65
#define R_alloc_x 66
#define R_compute_identical_x 67
#define R_do_MAKE_CLASS_x 68
#define R_do_new_object_x 69
#define R_do_slot_x 70
#define R_do_slot_assign_x 71
#define R_getClassDef_x 72
#define R_getContextCall_x 73
#define R_getContextEnv_x 74
#define R_getContextFun_x 75
#define R_getContextSrcRef_x 76
#define R_getGlobalFunctionContext_x 77
#define R_getParentFunctionContext_x 78
#define R_has_slot_x 79
#define R_insideBrowser_x 80
#define R_isEqual_x 81
#define R_isGlobal_x 82
#define R_lsInternal3_x 83
#define R_new_custom_connection_x 84
#define R_tryEval_x 85
#define R_unLockBinding_x 86
#define Rf_GetOption1_x 87
#define Rf_NonNullStringMatch_x 88
#define Rf_PairToVectorList_x 89
#define Rf_ScalarDouble_x 90
#define Rf_ScalarInteger_x 91
#define Rf_ScalarLogical_x 92
#define Rf_ScalarString_x 93
#define Rf_VectorToPairList_x 94
#define Rf_allocArray_x 95
#define Rf_allocMatrix_x 96
#define Rf_allocVector_x 97
#define Rf_any_duplicated_x 98
#define Rf_asChar_x 99
#define Rf_asCharacterFactor_x 100
#define Rf_asInteger_x 101
#define Rf_asLogical_x 102
#define Rf_asReal_x 103
#define Rf_classgets_x 104
#define Rf_coerceVector_x 105
#define Rf_cons_x 106
#define Rf_copyListMatrix_x 107
#define Rf_copyMatrix_x 108
#define Rf_copyMostAttrib_x 109
#define Rf_defineVar_x 110
#define Rf_dunif_x 111
#define Rf_duplicate_x 112
#define Rf_error_x 113
#define Rf_errorcall_x 114
#define Rf_eval_x 115
#define Rf_findFun_x 116
#define Rf_findVar_x 117
#define Rf_findVarInFrame_x 118
#define Rf_findVarInFrame3_x 119
#define Rf_getAttrib_x 120
#define Rf_gsetVar_x 121
#define Rf_inherits_x 122
#define Rf_install_x 123
#define Rf_installChar_x 124
#define Rf_isNull_x 125
#define Rf_isString_x 126
#define Rf_lengthgets_x 127
#define Rf_match_x 128
#define Rf_mkCharLenCE_x 129
#define Rf_namesgets_x 130
#define Rf_ncols_x 131
#define Rf_nrows_x 132
#define Rf_protect_x 133
#define Rf_punif_x 134
#define Rf_qunif_x 135
#define Rf_runif_x 136
#define Rf_setAttrib_x 137
#define Rf_str2type_x 138
#define Rf_unprotect_x 139
#define Rf_unprotect_ptr_x 140
#define Rf_warning_x 141
#define Rf_warningcall_x 142
#define Rprintf_x 143
#define SETCADR_x 144
#define SETCAR_x 145
#define SETCDR_x 146
#define SET_NAMED_FASTR_x 147
#define SET_RDEBUG_x 148
#define SET_RSTEP_x 149
#define SET_S4_OBJECT_x 150
#define SET_STRING_ELT_x 151
#define SET_SYMVALUE_x 152
#define SET_TAG_x 153
#define SET_TYPEOF_FASTR_x 154
#define SET_VECTOR_ELT_x 155
#define STRING_ELT_x 156
#define SYMVALUE_x 157
#define TAG_x 158
#define TYPEOF_x 159
#define UNSET_S4_OBJECT_x 160
#define VECTOR_ELT_x 161
#define forceSymbols_x 162
#define getCCallable_x 163
#define getConnectionClassString_x 164
#define getOpenModeString_x 165
#define getSummaryDescription_x 166
#define isSeekable_x 167
#define octsize_x 168
#define registerCCallable_x 169
#define registerRoutines_x 170
#define restoreHandlerStacks_x 171
#define setDotSymbolValues_x 172
#define unif_rand_x 173
#define useDynamicSymbols_x 174

#define UPCALLS_TABLE_SIZE 175

#endif // RFFI_UPCALLSINDEX_H
