#!/usr/bin/env bash
JAVA_ARGS=()
PROGRAM_ARGS=()
for opt in "${@:1}"
do
  case $opt in
    -J:*)
      opt=${opt:3}
      JAVA_ARGS+=("$opt") ;;
    *)
      PROGRAM_ARGS+=("$opt") ;;
  esac
done

exec java "${JAVA_ARGS[@]}" -cp %%CLASSPATH com.oracle.truffle.r.launchers.RCommand "${PROGRAM_ARGS[@]}"
