#!/usr/bin/env bash
#
# Copyright (c) 2020, Oracle and/or its affiliates. All rights reserved.
# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
#
# This code is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License version 3 only, as
# published by the Free Software Foundation.
#
# This code is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# version 3 for more details (a copy is included in the LICENSE file that
# accompanied this code).
#
# You should have received a copy of the GNU General Public License version
# 3 along with this work; if not, write to the Free Software Foundation,
# Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
#
# Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
# or visit www.oracle.com if you need additional information or have any
# questions.
#

# This script is deployed as <FASTR>/bin/configure_fastr.sh

source="${BASH_SOURCE[0]}"
# "un-link" the source path
while [ -h "$source" ] ; do
  prev_source="$source"
  source="$(readlink "$source")";
  if [[ "$source" != /* ]]; then
    # if the link was relative, it was relative to where it came from
    dir="$( cd -P "$( dirname "$prev_source" )" && pwd )"
    source="$dir/$source"
  fi
done

function printHelp {
  if [[ "$OSTYPE" == "darwin"* ]]; then
    echo "Checks presence of FastR dependencies and configures the paths in dynamic libraries accordingly."
    echo "usage: configure_fastr [--help] [--macos-no-homebrew] [--gcc-lib-path <path>]"
  else
    echo "Checks presence of FastR dependencies."
    echo "usage: configure_fastr [--help]"
  fi    
    
  if [[ "$OSTYPE" == "darwin"* ]]; then
    echo ""
    echo "optional arguments:"
    echo "  --gcc-lib-path <path>                       Use the <path> to locate the required gfortran libraries."
    echo "  --macos-no-homebrew                         Allows the script to proceed even if the target system does not have homebrew"
  fi
}

GCC_LIB_PATH=""
NO_BREW=0
while [[ $# -gt 0 ]]; do
  case $1 in
    --help)
      printHelp
      exit 0
    ;;
    --gcc-lib-path)
      shift
      GCC_LIB_PATH=$1
    ;;
    --macos-no-homebrew)
      NO_BREW=1
    ;;
    *)
      >&2 echo "Unknown option '$1'"
      printHelp
      exit 1
    ;;
  esac
  shift
done

(
  if [[ "$OSTYPE" == "linux-gnu" ]]; then
    if ! command -v ldconfig>/dev/null; then
      >&2 echo "Tool 'ldconfig' is not available. Maybe you need to run this as a root?"
      exit 2
    fi
    res=0
    if ! ldconfig -p | grep --quiet "libgomp.so.1"; then
      echo "Error: could not find OpenMP runtime library: libgomp.so.1"
      echo "Please install the OpenMP runtime library runtime libraries:"
      echo "    On Debian based systems: apt-get install libgomp1"
      echo "    On Oracle Linux: yum install libgomp"
      echo "    Note: Oracle Linux 8 should contain libgomp by default"
      res=1
    fi
    if [[ $res != 0 ]]; then
      echo "The basic configuration of FastR failed."
      echo "To learn more:"
      echo "  run this script with '--help'"
      echo "  visit https://www.graalvm.org/docs/reference-manual/languages/r"
      exit 1
    else
      echo "The basic configuration of FastR was successfull."
      echo ""
      echo "Note: if you intend to install R packages you may need additional dependencies."
      echo "The following packages should cover the most commonly used R packages:"
      echo "    On Debian based systems: apt-get install build-essential gfortran libxml2 libc++-dev"
      echo "    On Oracle Linux: yum groupinstall 'Development Tools' && yum install gcc-gfortran"
    fi
  elif [[ "$OSTYPE" == "darwin"* ]]; then
  else
    echo "Unknown operating system."
    echo "FastR may still work."
    echo "Make sure that GCC including gfortran and OpenMP is installed on your system."
  fi

  if [[ $CONFIGURE_ETC = 1 ]]; then
    export GRAALVM_VERSION=`grep -o 'GRAALVM_VERSION=.*' "../../../../release" | cut -d= -f2`
    cd ../etc
    echo "Running the configure script..."
    ./configure --with-x=no --with-aqua=no --enable-memory-profiling FFLAGS=-O2 $CONFIGURE_ARGS > configure.log 2>&1
    res=$?
    if [[ $res != 0 ]]; then
      echo "The configuration step failed."
    echo "The log was saved into ${PWD}/configure.log"
    echo "FastR may still work, but compilation of some R packages may fail"
    exit 1
  fi
  ed Makeconf < edMakeconf.etc > /dev/null 2>/dev/null
  export R_DEFAULT_PACKAGES=base
  R_LIBS_USER=`"../bin/R" --slave -e 'cat(path.expand(Sys.getenv("R_LIBS_USER")))'`
  echo "Creating user specific library directory: $R_LIBS_USER"
  mkdir -p "$R_LIBS_USER"
  echo "DONE"
  fi

)
