#!/bin/bash
#
# Copyright (c) 2017, 2018, Oracle and/or its affiliates. All rights reserved.
# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
#
# This code is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License version 2 only, as
# published by the Free Software Foundation.
#
# This code is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# version 2 for more details (a copy is included in the LICENSE file that
# accompanied this code).
#
# You should have received a copy of the GNU General Public License version
# 2 along with this work; if not, write to the Free Software Foundation,
# Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
#
# Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
# or visit www.oracle.com if you need additional information or have any
# questions.
#

if [[ "$FASTR_RFFI" != 'llvm-only' ]]; then
	g++ "$@"
fi
if [[ "$FASTR_RFFI" == 'nfi-only' ]]; then
    exit 0
fi

SOURCE="$0"
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

. $DIR/llvm-helper

errorOccurred || {
try
(

fortran=0
analyze_args "$@"

if [ $is_link -eq 1 ]
then
  extraObj=""
  if [ -f "$R_PACKAGE_DIR/libobjects" ]; then
     extraObj=`cat "$R_PACKAGE_DIR/libobjects"`
  fi
  create_bc_lib $@ $extraObj
else
  llvm_tool=clang++
  get_llvm_tool
  unamestr=`uname`
  if [[ "$unamestr" == 'Linux' ]]; then
    llvm_args="-stdlib=libc++ -I/usr/include/libcxxabi $llvm_args"
  fi
  runit $llvm_tool_bin $llvm_args
  ecode=$?
  if [[ $ecode -ne 0 ]]; then
    exit $ecode
  fi

  # the llvm_ir_file is empty if the result is sent to stdout
  if [ -n "$llvm_ir_file" ]; then
    mem2reg_opt
    ecode=$?
    if [[ $ecode -ne 0 ]]; then
      exit $ecode
    fi
    #fake_obj
    #ecode=$?
    #if [[ $ecode -ne 0 ]]; then
    #  exit $ecode
    #fi
  fi
fi

) || catch || {
	recordError
}
}

