setRefClass('A5R5', methods = list(foo = function() { print('A5R5$foo') }))
setRefClass('B5R5', methods = list(foo = function() { print('B5R5$foo') }))
C5R5 <- setRefClass('C5R5', contains = c('A5R5', 'B5R5'))
obj <- C5R5$new()
obj$foo()